@startuml

title Docker Image Build Config

set namespaceseparator ::

"::Dockerro::DockerImageBuildConfig" : +string git_url
"::Dockerro::DockerImageBuildConfig" : +string git_commit
"::Dockerro::DockerImageBuildConfig" : +string base_image_tag
"::Dockerro::DockerImageBuildConfig" : +bool template
"::Dockerro::DockerImageBuildConfig" : +string activation_key_prefix

::Dockerro::DockerImageBuildConfig "*" --> "1" ::Katello::ContentViewVersion : uses content from >
::Katello::ContentViewVersion "1..*" --> "1" ::Katello::ContentView : is version of >
::Katello::ContentView "1..*" --> "1" ::Organization : belongs to >

::Dockerro::DockerImageBuildConfig "*" --> "1" ::Katello::Repository : pushes to >

::Dockerro::DockerImageBuildConfig "0..1" --> "0..1" ::Katello::DockerImage : builds from >

::Katello::DockerImage "0..1" --> "0..1" ::Dockerro::DockerImageBuildConfig : built using >
::Katello::DockerImage "*" --> "0..1" ::Katello::DockerImage : is built from >
::Katello::DockerTag "*" --> "1" ::Katello::DockerImage : tags >

@enduml